### ISSUE TITLE
[1.14(.1)] Unable to join non-vanilla servers with custom server core

### ISSUE THREAD

**Issue by fixator10** [FabricMC/fabric#181]
PaperMC/Waterfall#366
shedaniel/RoughlyEnoughItems#74

When mod with packed Fabric API is installed, i unable to connect "custom-core" servers (BungeeCord, FML, "BeeCord" _(hivemc custom core)_), vanilla, or just plain Fabric Loader is fine, however.

After "Encrypting", on "Joining World" connection interrupts with reason 
`Internal Exception: net.minecraft.net_class151: Non [a-z0-9/._-] character in path of location: minecraft:BungeeCord`
`Internal Exception: net.minecraft.net_class151: Non [a-z0-9/._-] character in path of location: minecraft:FML`

Happens on 1.14 and 1.14.1

### Technical Info:
Launcher: MultiMC5 `0.6.5-develop-1308`
Fabric API version: v0.2.7+build.127 (in "modpack" included with `Autofish`, `i-am-very-smart`, `REI`)
Mods:
```
  auto-config-1.0.1+mc1.14
  Autofish-0.8.2-fabric-mc1.14
  BBOutlineReloaded-1.0.11-1.14-fabric
  blockmeter-1.0.1
  ClothEvents-0.3.1.23
  CustomSelectionBox-3.2.0
  durabilityviewer-1.14-fabric0.2.7-1.5
  easierchests-1.14-fabric0.2.7-1.3.1
  FabricProxy-1.0.0
  Hwyla-fabric-1.14-1.9.16-60
  i-am-very-smart-1.0.0+mc1.14
  malilib-fabric-1.14.0-0.9.5
  metatips-1.1.4+1.14
  ModMenu-1.5.3-84
  mousewheelie-1.1.5+1.14
  REIAddons-1.1.0
  RoughlyEnoughItems-2.9.110
  tweakeroo-fabric-1.14.0-0.9.3
```
[Logs](https://paste.ee/p/50pUn)

**Comment by modmuss50** [comment]
Fabric api 0.3 should fix this, can you test?

**Comment by fixator10** [comment]
`fabric-api-0.3.0-pre+build.156.jar` (latest version from [curseforge](https://minecraft.curseforge.com/projects/fabric/files))

Same excepetion:
![Internal Exception: net.minecraft.net_class151: Non [a-z0-9/._-] character in path of location: minecraft:BungeeCord](https://Moeka.is-a-good-waifu.com/2MnaFcL.png)
[Logs](https://paste.ee/p/JgVF6)

Mods:
```
  auto-config-1.0.1+mc1.14
  Autofish-0.8.2-fabric-mc1.14
  BBOutlineReloaded-1.0.11-1.14-fabric
  blockmeter-1.0.1
  ClothEvents-0.3.1.23
  CustomSelectionBox-3.2.0
  durabilityviewer-1.14-fabric0.2.7-1.5
  easierchests-1.14-fabric0.2.7-1.3.1
  fabric-api-0.3.0-pre+build.156
  FabricProxy-1.0.0
  Hwyla-fabric-1.14-1.9.16-60
  i-am-very-smart-1.0.0+mc1.14
  malilib-fabric-1.14.0-0.9.5
  metatips-1.1.4+1.14
  ModMenu-1.5.3-84
  mousewheelie-1.1.5+1.14
  REIAddons-1.1.0
  RoughlyEnoughItems-2.9.110
  tweakeroo-fabric-1.14.0-0.9.3
```

**Comment by fixator10** [comment]
Attempt №2: Disabled mods that include old version of Fabric API (Autofish, i-am-very-smart, REI)

Still the same
[Logs](https://paste.ee/p/gcM74)
[MultiMC Console Log](https://paste.ee/p/VeWGN)

**Comment by MamiyaOtaru** [comment]
fabric-api-0.3.0-pre+build.156 and fabric-resource-loader-v0-0.1.0+f1618918 in gradle: gradlew runClient works fine and I can connect to hypixel.  gradlew build, mod and fabric-api-0.3.0-pre+build.156.jar to .minecraft/mods I get the same error as in the screenshot above when trying to connect.

Removing fabric-networking .jar from fabric-api-0.3.0-pre+build.156.jar/META-INF/jars (and others that use it, like fabric-registry-sync etc) again allows me to join hypixel.  Can't say for sure which of them fixes it, as a bunch have to be removed at once to even be able to launch

**Comment by liach** [comment]
So fabric networking should use some sort of fake identifier for packet id instead of the strict java edition identifier.
